#%RAML 0.8
title: Squash Reservation
version: "1.0.0"
baseUri: "http://example.com/v1"
schemas: 
    - 
        Terrain: '{"type":"object","$schema":"http://json-schema.org/draft-03/schema#","title":"Terrain","properties":{"id":{"type":"integer","required":true,"title":"id"},"available":{"type":"boolean","required":false,"title":"available"}}}'
    - 
        Reservation: '{"type":"object","$schema":"http://json-schema.org/draft-03/schema#","title":"Reservation","properties":{"id":{"type":"integer","required":true,"title":"id"},"heure_reservation":{"type":"string","required":false,"title":"heure_reservation"},"id_terrain":{"type":"integer","required":false,"title":"id_terrain"}}}'
/reservation: 
    get: 
        displayName: Get Reservation
        queryParameters: 
            id: 
                displayName: id
                type: integer
                required: true
                repeat: false
                example: /reservation/?id=1
        responses: 
            "200": 
                body: 
                    application/json: 
                        schema: Reservation
                        example: '[{"id":1,"heure_reservation":null,"id_terrain":1}]'
            "404": 
                body: 
                    application/json: 
                        schema: Reservation
                        example: '[{"id":1,"heure_reservation":null,"id_terrain":1}]'
    put: 
        displayName: Update Reservation
        queryParameters: 
            id: 
                displayName: id
                type: integer
                required: true
                repeat: false
                example: '{"id" : "1"}'
            id_terrain: 
                displayName: id_terrain
                type: integer
                required: false
                repeat: false
                example: '{"id_terrain" : "1"}'
            heure_reservation: 
                displayName: heure_reservation
                type: string
                required: false
                repeat: false
                example: '{"heure_reservation" : "01-01-1970 17"}'
        responses: 
            "200": 
                body: 
                    application/json: 
                        schema: Reservation
                        example: '{"id":1,"heure_reservation":null,"id_terrain":1}'
            "400": 
                description: Mauvais format de date en entrée
                body: 
                    application/json: 
                        schema: Reservation
                        example: '{"id":1,"heure_reservation":null,"id_terrain":1}'
            "404": 
                description: Id de réservation introuvable
                body: 
                    application/json: 
                        schema: Reservation
                        example: '{"id":1,"heure_reservation":null,"id_terrain":1}'
            "406": 
                description: Pas de paramètre id envoyé
                body: 
                    application/json: 
                        schema: Reservation
                        example: '{"id":1,"heure_reservation":null,"id_terrain":1}'
            "409": 
                description: Le terrain est déjà pris à cette heure, modification impossible
                body: 
                    application/json: 
                        schema: Reservation
                        example: '{"id":1,"heure_reservation":null,"id_terrain":1}'
    delete: 
        displayName: Delete Reservation
        queryParameters: 
            id: 
                displayName: id
                type: integer
                required: true
                repeat: false
                example: /reservation/1
        responses: 
            "200": 
                body: 
                    application/json: 
                        schema: Reservation
                        example: '{"id":1,"heure_reservation":null,"id_terrain":1}'
            "404": 
                body: 
                    application/json: 
                        schema: Reservation
                        example: '{"id":1,"heure_reservation":null,"id_terrain":1}'
    post: 
        displayName: Create Reservation
        queryParameters: 
            heure_reservation: 
                displayName: heure_reservation
                type: string
                required: true
                repeat: false
                example: '{"heure_reservation" : "01-01-1970 17"}'
        responses: 
            "200": 
                body: 
                    application/json: 
                        schema: Reservation
                        example: '{"id":1,"heure_reservation":null,"id_terrain":1}'
            "400": 
                description: Mauvais format de date
                body: 
                    application/json: 
                        schema: Reservation
                        example: '{"id":1,"heure_reservation":null,"id_terrain":1}'
            "401": 
                description: Date en paramètre antérieure à la date du jour
                body: 
                    application/json: 
                        schema: Reservation
                        example: '{"id":1,"heure_reservation":null,"id_terrain":1}'
            "404": 
                description: Pas de date entrée en paramètre
                body: 
                    application/json: 
                        schema: Reservation
                        example: '{"id":1,"heure_reservation":null,"id_terrain":1}'
            "409": 
                description: Tout les terrains sont résérvés à cette heure
                body: 
                    application/json: 
                        schema: Reservation
                        example: '{"id":1,"heure_reservation":null,"id_terrain":1}'
/terrain: 
    get: 
        displayName: Get terrain
        queryParameters: 
            id: 
                displayName: id
                type: integer
                required: false
                repeat: false
                example: /terrain/?id=1
        responses: 
            "200": 
                body: 
                    application/json: 
                        schema: Terrain
                        example: '{"id":1,"available":false}'
            "404": 
                body: 
                    application/json: 
                        schema: Terrain
                        example: '{"id":1,"available":false}'
    put: 
        displayName: Update terrain
        queryParameters: 
            id: 
                displayName: id
                type: integer
                required: true
                repeat: false
                example: '{"id" : "1"}'
            available: 
                displayName: available
                type: boolean
                required: false
                repeat: false
        responses: 
            "200": 
                body: 
                    application/json: 
                        schema: Terrain
                        example: '{"id":1,"available":false}'
            "406": 
                description: Pas de paramètre id entré
                body: 
                    application/json: 
                        schema: Terrain
                        example: '{"id":1,"available":false}'
    delete: 
        displayName: Delete terrain
        queryParameters: 
            id: 
                displayName: id
                type: integer
                required: true
                repeat: false
                example: /terrain/1
        responses: 
            "200": 
                body: 
                    application/json: 
                        schema: Terrain
                        example: '{"id":1,"available":false}'
            "404": 
                body: 
                    application/json: 
                        schema: Terrain
                        example: '{"id":1,"available":false}'
    post: 
        displayName: Create terrain
        queryParameters: 
            available: 
                displayName: available
                type: boolean
                required: true
                repeat: false
        responses: 
            "200": 
                body: 
                    application/json: 
                        schema: Terrain
                        example: '{"id":1,"available":false}'
            "404": 
                body: 
                    application/json: 
                        schema: Terrain
                        example: '{"id":1,"available":false}'
